export const ADD_COLUMN = "ADD_COLUMN"
export const ADD_ITEM = "ADD_ITEM"
export const CHANGE_COLUMN_NAME = "CHANGE_COLUMN_NAME"
export const DELETE_COLUMN = "DELETE_COLUMN"
export const SET_CURRENT_CLIP_PAD = "SET_CURRENT_CLIP_PAD"
export const CHANGE_ITEM = "CHANGE_ITEM"
export const DELETE_ITEM = "DELETE_ITEM"
export const ADD_CLIP_PAD = "ADD_CLIP_PAD"
export const CHENGE_CLIP_PAD_NAME = "CHENGE_CLIP_PAD_NAME"
export const CHENGE_CLIP_PAD_EMAIL = "CHENGE_CLIP_PAD_EMAIL"
export const ADD_USER = "ADD_USER"


